name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      OPERATON_SKIP_HEALTH_CHECK: 'true'
      OPERATON_BASE_URL: 'http://localhost:8080/engine-rest'
      OPERATON_USERNAME: 'demo'
      OPERATON_PASSWORD: 'demo'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci
      - name: Check license headers
        run: npm run check:license
      - name: Check commit messages
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}
      - run: npm run build
      - run: npm test
